name: Store CVS Service
description: Store CVS Lambda Service Artefacts in S3

inputs:
  service_names:
    description: The service name
    required: true
  environment_name:
    description: The environment name
    required: true
  access_token:
    description: GitHub Access Token
    required: true
  s3_bucket:
    description: S3 Bucket for Service Artefacts
    required: true

runs:
  using: composite
  steps:

    - name: Generate SHA256
      id: artefact
      shell: bash
      run: |
        echo -n ${{ github.sha }} > hash.txt
        cp artifacts/${{ inputs.service_name }}*.zip ${{ inputs.service_name }}-${{ github.sha }}.zip
        LAMBDA_SHA=$(openssl dgst -sha256 -binary ${{ inputs.service_name }}-${{ github.sha }}.zip | openssl enc -base64)
        echo "lambda_sha=$LAMBDA_SHA" >> $GITHUB_OUTPUT
        
    - name: Upload to S3
      shell: bash
      run: |
        aws s3 cp hash.txt "s3://${{ inputs.s3_bucket }}/${{inputs.service_name }}/latestHash_${{ inputs.environment_name }}.txt --metadata "sha256sum=${{ steps.artefact.outputs.lambda_sha }}"
        aws s3 cp ${{ inputs.service_name }}-${{ github.sha }}.zip "s3://${{ inputs.s3_bucket }}/${{inputs.service_name }}/${{ github.sha }}.zip" --metadata "sha256sum=${{ steps.artefact.outputs.lambda_sha }},Tag=${{ inputs.service_name }},commit=${{ github.sha }}"