name: Store CVS Service
description: Store CVS Lambda Service Artefacts in S3

inputs:
  environment_name:
    description: The environment name
    required: true
  access_token:
    description: GitHub Access Token
    required: true
  s3_bucket:
    description: S3 Bucket for Service Artefacts
    required: true

runs:
  using: composite
  steps:
    - name: Get Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-artifacts-${{ github.event.pull_request.number || github.run_id }}

    - name: Convert and Upload
      shell: bash
      run: |
        for f in $(ls artifacts/*.zip); do
          LAMBDA_SHA=$(openssl dgst -sha256 -binary ${f} | openssl enc -base64)
          echo -n ${{ github.sha }} | aws s3 cp - s3://${{ inputs.s3_bucket }}/${f%-*-*}/latestHash_${{ inputs.environment_name }}.txt --content-type "text/plain" 2>&1
          aws s3 cp ${f} "s3://${{ inputs.s3_bucket }}/${f%-*-*}/${{ github.sha }}.zip" --metadata "sha256sum=${LAMBDA_SHA},Tag=${{ inputs.service_name }},commit=${{ github.sha }}"
        done        

