name: Install Liquibase
description: Install Liquibase

inputs:
  liquibase_version:
    description: Version of Liquibase to use
    default: 4.33.0
  mysql_connector_java_version:
    description: Version of MySQL Connector to use
    default: 8.0.33

runs:
  using: composite
  steps:

    - name: Install Liquibase
      shell: bash
      run: |
        # Install Liquibase
        curl -L https://github.com/liquibase/liquibase/releases/download/v${{ inputs.liquibase_version }}/liquibase-${{ inputs.liquibase_version }}.zip --output liquibase-${{ inputs.liquibase_version }}.zip
        unzip -oq -d liquibase liquibase-${{ inputs.liquibase_version }}.zip
    
    - name: Download MySQL connector
      shell: bash
      run: |
        echo "$GITHUB_WORKSPACE/liquibase" >> $GITHUB_PATH
        mkdir -p $GITHUB_WORKSPACE/liquibase/lib
        curl -L https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-${{ inputs.mysql_connector_java_version }}.tar.gz --output mysql-connector-j.tar.gz
        tar -zxf mysql-connector-j.tar.gz
        mv -v mysql-connector-j-${{ inputs.mysql_connector_java_version }}/mysql-connector-j-${{ inputs.mysql_connector_java_version }}.jar $GITHUB_WORKSPACE/liquibase/lib/