name: "GitHub Failure Notifier"
description: "Notifies Teams and/or email when a GitHub job fails."
inputs:
  teams-webhook:
    description: "Microsoft Teams webhook URL"
    required: false
  notify-email:
    description: "Send an email notification"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Get Commit Author Email
      shell: bash
      id: get-email
      run: |
        COMMIT_EMAIL="${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        ALT_EMAIL="${{ github.actor }}@users.noreply.github.com"
        echo "commit-email=$COMMIT_EMAIL" >> $GITHUB_ENV
        echo "alt-email=$ALT_EMAIL" >> $GITHUB_ENV
      

    - name: Send Teams Notification
      shell: bash
      if: ${{ inputs.teams-webhook }}
      env:
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        JOB: ${{ github.job }}
        ACTOR: ${{ github.actor }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{
          \"text\": \"**🚨 GITHUB JOB FAILED 🚨**\\n\\n
          **Repo:** $REPO\\n
          **Branch:** $BRANCH\\n
          **Failed Job:** $JOB\\n
          🔄 **Triggered by:** $ACTOR\"
        }" "${{ inputs.teams-webhook }}"

    - name: Install mailutils
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y mailutils

    - name: Send Email Notification
      shell: bash
      if: ${{ inputs.notify-email == 'true' }}
      run: |
        echo "GitHub Job Failed for ${{ github.repository }}" | mail -s "🚨 GitHub Job Failed" "$commit-email"