name: Remove Hash Files
description: Remove Hash Files for a given environment

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  service-bucket:
    description: The bucket hosting the Hash Files (default `cvs-services`)
    default: cvs-services
  artefacts-bucket:
    description: The new bucket which is hosting the Hash files for updated services
    default: cvs-service-artefacts
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: 📃 Remove Hash Files
      id: remove_hash_files
      shell: bash
      run: |
        echo "🔍 Searching and removing hash files for '${{ inputs.environment-name }}.txt'"

        for BUCKET in "${{ inputs.service-bucket }}" "${{ inputs.artefacts-bucket }}"; do
          echo "🪣 Checking bucket: $BUCKET"
          hashes=$(aws s3api list-objects-v2 \
            --bucket "$BUCKET" \
            --query "Contents[?contains(Key, '${{ inputs.environment-name }}.txt')].Key" \
            | jq -r '.[]')

          for hash in $hashes; do
            echo "🗑️ Deleting $hash from $BUCKET"
            AWS_PROFILE=mgmt aws s3 rm s3://$BUCKET/$hash ${{ inputs.dry-run == 'true' && '--dryrun' || '' }}
          done
        done