name: Remove Hash Files
description: Remove Hash Files for a given environment

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  service-bucket:
    description: The bucket hosting the Hash Files (default `cvs-services`)
    default: '["cvs-services","cvs-service-artefacts"]'
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: 📃 Remove Hash Files
      id: remove_hash_files
      shell: bash
      run: |
        # Remove all hash files for ${{ inputs.environment-name }}
        buckets=$(echo '${{ inputs.service-bucket }}' | jq -r '.[]')
        for bucket in $buckets; do
          echo "🔍 Checking bucket: $bucket"
          hashes=$(aws s3api list-objects-v2 --bucket "$bucket" --query "Contents[?contains(Key, '${{ inputs.environment-name }}.txt')].Key" | jq -r '.[]')
          
          for hash in $hashes; do
            echo "🗑️ Removing: s3://$bucket/$hash"
            AWS_PROFILE=mgmt aws s3 rm s3://$bucket/$hash $([[ "${{ inputs.dry-run }}" == "true" ]] && echo "--dryrun")
          done
        done