name: Send Teams Notification
description: 'Send a notification to Teams channel via Webhook.'

inputs:
  webhook_url:
    description: 'The webhook URL to send the notification to.'
    required: true
  report-link:
    description: 'The link to the test reports.'
    required: false
  project:
    description: The project being tested
    required: true

runs:
  using: 'composite'
  steps:
    - name: Microsoft Teams Notification
      shell: bash
      run: |
        curl -X POST ${{ secrets.TEAMS_WEBHOOK_URL }} \
        -H "Content-Type: application/json" \
        -d '{
          "repository": "'"${GITHUB_REPOSITORY}"'",
          "branch": "'"${GITHUB_REF_NAME}"'",
          "workflow": "'"${GITHUB_WORKFLOW}"'",
          "status": "'"${{ job.status }}"'",
          "project": ${{ inputs.project }}",
          "workflow_url": "'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"'",
          "report_link": ${{ inputs.report-link }}"
        }'