ame: Terraform State Unlock
description: Perform an unlock of the terraform state file

inputs:
  options:
    description: Additional Terraform Options 
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'true'
  repository:
    description: The name of the repository
    default: 'cvs-tf'

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}

    - name: 🔓 Unlock State File 
      shell: bash
      env:
        environment_name: ${{ inputs.environment-name }}
        repository: ${{ inputs.repository }}
      run: |
        if [ "$repository" = "cvs-tf" ]; then
          bucket="${repository}-environment"
        else
          bucket="$repository"
        fi

        key="${bucket}/env:/${environment_name}/tf_state"

        echo "Using DynamoDB table: $bucket"
        echo "Looking up key: $key"

        lock_id=$(aws dynamodb get-item --table-name "$bucket" \
          --key "{\"LockID\": {\"S\": \"$key\"}}" \
          --attributes-to-get "Info" --profile "mgmt" | jq -r '.[].Info.S | fromjson | .ID')

        if [ -n "$lock_id" ]; then
          echo "Attempting to unlock Terraform state for $environment_name..."
          terraform force-unlock -force "$lock_id"
        else
          echo "No lock found for $environment_name"
        fi