ame: Terraform State Unlock
description: Perform an unlock of the terraform state file

inputs:
  options:
    description: Additional Terraform Options 
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  create-workspace:
    description: Should a new Terraform Workspace be created
    default: 'false'
  repository:
    description: The name of the repository
    default: 'cvs-tf'
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  region:
    description: The AWS Region resources exist in
    default: eu-west-1

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: ${{ inputs.create-workspace }}
        working-directory: ${{ inputs.working-directory }}
        backend: ${{ inputs.backend }}

    - name: 🔓 Unlock State File 
      shell: bash
      run: |
          echo "Environment Name: ${{ inputs.environment-name }}"
          echo "Repository: ${{ inputs.repository }}"

          if [ "${{ inputs.backend }}" = "true" ]; then
            # Use legacy state file location
            bucket="cvs-tf-environment"
            key="${bucket}/env:/${environment_name}/tf_state"
          else
            # use new standard state file location
            bucket="cvs-tf-state-${{ inputs.region }}"
            key="${bucket}/${{ env.TF_AWS_ACCOUNT_NAME }}/${environment_name}/${{ inputs.repository }}"
          fi

          # Check for Lock File
          AWS_PROFILE=mgmt
          echo "Key: ${key}"
          if [[ $(aws s3 ls "s3://${key}.tflock") ]]; then
            echo "Removing S3 Lockfile for $${{ inputs.environment-name }}"
            aws s3 rm "s3://${key}.tflock"

          else
            echo "No TF File Lock found, looking for Dynano Table Lock"

            echo "Using DynamoDB table: ${bucket}"
            echo "Looking up key: ${key}"

            lock_id=$(aws dynamodb get-item --table-name "${bucket}" \
              --key "{\"LockID\": {\"S\": \"$key\"}}" \
              --attributes-to-get "Info" --profile "mgmt" | jq -r '.[].Info.S | fromjson | .ID')

            if [ -n "${lock_id}" ]; then
              echo "Attempting to unlock Terraform state for $${{ inputs.environment-name }}..."
              terraform force-unlock -force "$lock_id" <<< "yes"
            else
              echo "No lock found for $environment_name"
            fi
          fi