name: Terraform State File Unlock
description: Unlock Terraform state file after failure

inputs:
  environment-name:
    description: Environment with the locked state
    default: develop
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
    
runs:
  using: composite
  steps:
    - name: Unlock State File
      shell: bash
      run: |
        # Unlock Terraform
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}

        repository=${GITHUB_REPOSITORY##*/}
        echo "Environment Name: ${{ inputs.environment-name }}"
        echo "Repository: ${repository}"

        if [[ '${{ inputs.backend }}' == 'false' ]]; then
          repository="${repository}-environment"
          key="${repository}/env:/${environment_name}/tf_state"
          echo "Using DynamoDB table: ${repository}"
          echo "Looking up key: ${key}"

          lock_id=$(aws dynamodb get-item --table-name "$bucket" \
          --key "{\"LockID\": {\"S\": \"$key\"}}" \
          --attributes-to-get "Info" \
          --profile "mgmt" \
          | jq -r '.[].Info.S | fromjson | .ID')

        else
          lock_id=$(aws dynamodb get-item --table-name ${{ env.TF_BACKEND }} \
          --key '{"LockID":{"S": "${{ env.TF_BACKEND }}/${{ env.TF_AWS_ACCOUNT_NAME }}:/${{ env.TF_VAR_AWS_ENVIRONMENT }}/${{ env.TF_VAR_DVSA_SERVICE }}"}}' \
          --attributes-to-get Info \
          | jq -r '.[].Info.S | fromjson | .ID')
        fi

        if [ -n "${lock_id}" ]; then
          echo "Attempting to unlock Terraform state..."
          terraform force-unlock ${lock_id} <<< "yes"
        else	
          echo "No lock found for ${environment_name}"	
        fi