name: Terraform Initialize
description: Initialize Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  backend:
    description: Use a custom Backend Configuration
    default: 'false'
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  create-workspace:
    description: Create new Workspace if required
    default: 'true'

runs:
  using: composite
  steps:
    - name: Configure Terraform
      id: terraform_config
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Initialize Terraform
      id: terraform_init
      shell: bash
      run: |
        # Initialize ${{ inputs.environment-name }}
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        if [[ ! -f ".terraform/environment" ]]; then
          terraform init -upgrade${{ inputs.backend == 'true' && format(' -backend-config="workspace_key_prefix={0}"', env.TF_AWS_ACCOUNT_NAME) || '' }}
          terraform workspace select${{ inputs.create-workspace == 'true' && ' -or-create' || '' }} ${{ inputs.environment-name }} \
          && $(echo "Workspace: ${{ inputs.environment-name }}" >> $GITHUB_STEP_SUMMARY)
        fi  
 