name: Terraform Destroy
description: Destroy an Environment using Terraform

inputs:
  environment-name:
    description: Environment Identifier (e.g. `cb2-1099`)
    required: true
  terraform-version:
    description: The version of Terraform to use (defaults to 1.7.3)
    default: 1.7.3
  encryption-key:
    description: ARN of a KMS Key to use for Encryption
    required: false
  infracost-key:
    description: API Key for InfraCost
  tfvars:
    description: Should a TFVARS file be used
    default: 'false'
  backend:
    description: Use a custom Backend Configuration
    default: 'false'  
  working-directory:
    description: If the Terraform is not in the root of the folder, provide the working working directory
    required: false
  dry-run:
    description: Don't perform action, just output information
    default: "true"

runs:
  using: composite
  steps:
    - name: Initialize Terraform
      uses: dvsa/cvs-github-actions/terraform-initialize@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: 'false'
        working-directory: ${{ inputs.working-directory }}
        backend: ${{ inputs.backend }}

    - name: Refresh Terraform
      shell: bash
      env:
        AWS_PROFILE: main
      run: terraform refresh

    - name: Remove VPC Connections
      shell: bash   
      env:
        AWS_PROFILE: main     
      run: |
        # Remove all Lambda VPC Connections
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        for lambda in $(terraform show -no-color | grep -E '\s+arn\s+=\s.*:lambda.*' | sed -E 's/.*"(.*:lambda.*:function:[a-z0-9-]+).*"/\1/' | sort | uniq); do
          echo "${{ inputs.dry-run == 'true' && '(dryrun) ' || '' }}remove: ${lambda}"
          ${{ inputs.dry-run == 'true' && 'echo ' || '' }}aws lambda update-function-configuration --function-name ${lambda} --vpc-config '{"SubnetIds":[], "SecurityGroupIds":[]}' >/dev/null
        done

    - name: Terraform Plan
      id: plan
      uses: dvsa/cvs-github-actions/terraform-plan@develop
      with:
        options: '-destroy'
        validate: 'false'
        environment-name: ${{ inputs.environment-name }}
        terraform-version: ${{ inputs.terraform-version }}
        create-workspace: 'false'
        encryption-key: ${{ inputs.encryption-key }}
        infracost-key: ${{ inputs.infracost-key }}
        tfvars: ${{ inputs.tfvars }}
        backend: ${{ inputs.backend }}
        working-directory: ${{ inputs.working-directory }}

    - name: Terraform Apply
      if: ${{ inputs.dry-run == 'false' && steps.plan.outputs.changes-detected == 'true' }}
      uses: dvsa/cvs-github-actions/terraform-apply@develop
      with:
        terraform-version: ${{ inputs.terraform-version }}
        environment-name: ${{ inputs.environment-name }}
        create-workspace: 'false'
        encryption-key: ${{ inputs.encryption-key }}
        backend: ${{ inputs.backend }}
        working-directory: ${{ inputs.working-directory }}
        
    - name: Remove Workspace
      if: ${{ inputs.dry-run == 'false' }}
      shell: bash
      run: |
        # Remove ${{ inputs.environment-name }} Workspace
        ${{ inputs.working-directory != '' && format('cd {0}', inputs.working-directory) || '' }}
        terraform workspace select default
        terraform workspace delete ${{ inputs.environment-name }} 
        echo "Terraform Workspace \`${{ inputs.environment-name }}\` Deleted!" >> $GITHUB_STEP_SUMMARY

    - name: Remove Hash Files
      id: remove_hash_files
      uses: dvsa/cvs-github-actions/hash-delete@develop
      with:
        environment-name: ${{ inputs.environment-name }}
        dry-run: ${{ inputs.dry-run }}

    - name: 🔓 Unlock State File
      if: failure() || cancelled()
      uses: dvsa/cvs-github-actions/terraform-state-unlock@develop
      with:
        working-directory: ${{ inputs.working-directory }}
        backend: ${{ inputs.backend }}