name: 'Terraform PR Comment'
description: 'Posts Terraform checks comment on a PR'
inputs:
  github-token:
    required: true
    description: 'GitHub token for authentication'
  fmt-exitcode:
    required: true
    description: 'Terraform format exit code'
  fmt-outcome:
    required: true
    description: 'Terraform format exit code'
  validate-exitcode:
    required: true
    description: 'Terraform validate exit code'
  plan-exitcode:
    required: true
    description: 'Terraform plan exit code'
  checkov-exitcode:
    required: true
    description: 'Checkov scan exit code'
runs:
  using: "composite"
  steps:

    - name: Parse exit codes
      id: parse_exitcode
      shell: bash
      run: |
        if [ "${{ inputs.fmt-exitcode }}" -eq 0 ]; then
          echo "fmt_result=success" >> $GITHUB_OUTPUT
        else
          echo "fmt_result=failure" >> $GITHUB_OUTPUT
        fi      
        if [ "${{ inputs.validate-exitcode }}" -eq 0 ]; then
          echo "validate_result=success" >> $GITHUB_OUTPUT
        else
          echo "validate_result=failure" >> $GITHUB_OUTPUT
        fi
        if [ "${{ inputs.plan-exitcode }}" -eq 0 ]; then
          echo "plan_result=success" >> $GITHUB_OUTPUT
        else
          echo "plan_result=failure" >> $GITHUB_OUTPUT
        fi
        if [ "${{ inputs.checkov-exitcode }}" -eq 0 ]; then
          echo "checkov_result=success" >> $GITHUB_OUTPUT
        else
          echo "checkov_result=failure" >> $GITHUB_OUTPUT
        fi

    - uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
          })

          const fs = require('fs');
          let checkovOutput = '';
          try {
            checkovOutput = fs.readFileSync('checkov-report-${{ github.run_id }}.md/results_github_failed_only.md', 'utf8');
          } catch (e) {
            checkovOutput = 'Checkov report not found.';
          }
          let planOutput = '';
          try {
            planOutput = fs.readFileSync('plan.txt', 'utf8');
          } catch (e) {
            planOutput = 'Terraform plan not found.';
          }

          // 2. Prepare format of the comment
          const output = `#### Terraform Format and Style 🖌\`${{ steps.parse_exitcode.outputs.fmt_result }}\`
          #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.parse_exitcode.outputs.validate_result }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ inputs.validate_stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.parse_exitcode.outputs.plan_result }}\`

          <details><summary>Terraform Plan</summary>

          ### Terraform Plan

          \`\`\`\n
          ${planOutput}
          \`\`\`

          </details>

          #### Checkov Scan 📖\`${{ steps.parse_exitcode.outputs.checkov_result }}\`

          <details><summary>Checkov scan output</summary>

          ${checkovOutput}

          </details>

          *Pusher: @${{ github.actor }}, Workflow: \`${{ github.workflow }}\`*`;

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }