name: 🌱 Seed Tables

on:
  workflow_call:
    inputs:
      environment:
        description: "The Environment to Seed (optional for manual runs)"
        required: false
        type: string
      dry-run:
        description: "Don't perform action, just output information"
        required: false
        type: boolean
        default: false
      branch:
        description: 'Branch to create or build'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      AWS_MGMT_ROLE:
        required: true

env:
  MGMT_AWS_ROLE: ${{ format('arn:aws:iam::{0}:role/{1}', fromJson(vars.AWS_ACCOUNTS_OLD)['mgmt'].id, vars.AWS_ROLE) }}
  ENV_AWS_ROLE: ${{ format('arn:aws:iam::{0}:role/{1}', fromJson(vars.AWS_ACCOUNTS_OLD)[inputs.environment || 'develop'].id, vars.AWS_ROLE) }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  environment:
    name: 🧹 Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      github-branch: ${{ steps.environment.outputs.github-branch }}
      environment-name: ${{ steps.settings.outputs.environment-name }}
      environment-type: ${{ steps.settings.outputs.environment-type }}
      service-name: ${{ steps.package.outputs.service-name }}
      seed-target: ${{ steps.seed-target.outputs.seed-target }}
      dry-run: ${{ steps.settings.outputs.dry-run }}
      env-aws-role: ${{ steps.set-role.outputs.env-aws-role }}

    steps:
      - name: 📥 Get Codebase
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: 📦 Read Package
        id: package
        run: |
          package=$(cat package.json | jq -c)
          echo "service-name=$(jq -rc '.name' <<< ${package})" >> $GITHUB_OUTPUT

      - name: ↕️ Get Environment Details
        id: environment
        uses: dvsa/cvs-github-actions/environment@develop
        with:
          environment: ${{ github.ref_name }}

      - name: 🎯 Seed Target
        id: seed-target
        run: |
          if [[ -e "serverless.yml" ]]; then
            seeds=$(yq '.custom.dynamodb.seed.dev.sources' serverless.yml -o json)
            if [[ "${seeds}" != "null" ]]; then
              seed=$(jq -c '. | to_entries | map({table:(.value.table | sub("\\w.+\\W-"; "")), seed_file:.value.sources.[]})' <<< "${seeds}")
              echo "seed-target=${seed}" >> $GITHUB_OUTPUT
            else
              echo "No tables to seed" >> $GITHUB_STEP_SUMMARY
            fi
          fi

      - name: Calculate Deployment Settings
        id: settings
        run: |
          dry_run=${{ inputs.dry-run }}
          environment_name=${{ steps.environment.outputs.environment-name }}
          environment_type=${{ steps.environment.outputs.environment-type }}

          echo "environment-name=${environment_name}" >> $GITHUB_OUTPUT
          echo "environment-type=${environment_type}" >> $GITHUB_OUTPUT
          echo "dry-run=${dry_run}" >> $GITHUB_OUTPUT

          echo "## Deployment Settings" >> $GITHUB_STEP_SUMMARY
          formatted_tables=$(jq -r 'map(.table | gsub("-"; " ")) | join(", ")' <<< '${{ steps.seed-target.outputs.seed-target }}') >> $GITHUB_STEP_SUMMARY
          echo "| Tables to Seed | ${formatted_tables} |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          echo "| TF Workspace | ${environment_name} |" >> $GITHUB_STEP_SUMMARY
          echo "| GitHub Environment | ${environment_type} |" >> $GITHUB_STEP_SUMMARY
          echo "| GitHub Branch | $([[ '${{ github.event_name }}' == 'schedule' ]] && echo 'main' || echo '${{ steps.environment.outputs.github-branch }}') |" >> $GITHUB_STEP_SUMMARY
          echo "| Dry Run | ${dry_run} |" >> $GITHUB_STEP_SUMMARY

  seed-tables:
    name: 🌱 Seed ${{ matrix.seed-target.table }}
    runs-on: ubuntu-latest
    needs: environment
    environment: ${{ needs.environment.outputs.environment-type }}
    strategy:
      matrix:
        seed-target: ${{ fromJson(needs.environment.outputs.seed-target) }}

    steps:
      - name: 📥 Get Codebase
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.branch }}

      - name: 🪪 Get Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ENV_AWS_ROLE }}
          aws-region: ${{ vars.DVSA_AWS_REGION }}
          role-session-name: gha_seed_tables_${{ needs.environment.outputs.service-name }}_${{ needs.environment.outputs.environment-name }}

      - name: 📇 Get Table Name
        id: table_name
        run: |
          table_name=$(aws dynamodb list-tables | jq -r '.TableNames[] | select(. | contains("cvs-${{ needs.environment.outputs.environment-type }}-${{ matrix.seed-target.table }}"))')
          echo "table-name=${table_name}" >> $GITHUB_OUTPUT

      - name: 🧹 Purge Table
        uses: dvsa/cvs-github-actions/table-purge@develop
        with:
          table: ${{ steps.table_name.outputs.table-name }}
          dry-run: ${{ needs.environment.outputs.dry-run }}

      - name: 🌱 Re-Seed Table
        uses: dvsa/cvs-github-actions/table-seed@develop
        if: ${{ !needs.environment.outputs.dry-run }}
        with:
          table: ${{ steps.table_name.outputs.table-name }}
          seed-file: ${{ matrix.seed-target.seed_file }}